### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gramss** [meiser/waage#1]
Would it be possible to add a license to your library?
I might want to add a few functions for a 82c device, but need to know if so can use your code for that.

Kind regards and a happy new year!

**Comment by skeller1** [comment]
Hi,

very old code from my first job after studying used in custom Infor LN /Baan ERP sessions.
Please feel free to clone the code.
**License added.**

Kind regards and a happy new year

**Comment by skeller1** [comment]
Some code parts (serial handling) were realized with Boost (https://www.boost.org/users/license.html)

**Comment by gramss** [comment]
Thank you for your fast response!

Having something to work with is always better then starting completley from scratch :)
